### ISSUE TITLE
Image Tagging

### ISSUE THREAD

**Issue by Fabian-K** [SAP/devops-docker-neo-cli#23]
Hi,

is it possible to maintain & publish image tags other than latest? I could imagine something like
`ppiper/neo-cli:1` always pointing to the latest 1.x.x release or `ppiper/neo-cli:1.89` always pointing to the latest 1.89.x release. This would support caching of images and/or not having surprises due to image updates.

Thanks,
Fabian

**Comment by marcusholl** [comment]
@radsoulbeard : this proposal goes into the same direction like what we do for `ppiper/cf-cli` ...

**Comment by o-liver** [comment]
We have this, the latest version being [v8](https://hub.docker.com/r/ppiper/neo-cli/tags) as of today.
