### ISSUE TITLE
Update to 1.113.10.2

### ISSUE THREAD

**Issue by lvhengel** [SAP/devops-docker-neo-cli#35]
Can you please update the docker container to the latest neo sdk.

Warning: Your SDK version "1.106.5" is no longer supported. The latest version is "1.113.10.2" and upgrade is highly recommended.

**Comment by yoovi4u** [comment]
I have the same problem.. 
Looks like there is a new version already..

"Warning: Your SDK version "1.106.5" is no longer supported. The latest version is "1.114.14" and upgrade is highly recommended"

**Comment by radsoulbeard** [comment]
Published
